### PR TITLE
ck/#35 thermal output models

### LINKED ISSUE #1: OutputModels for ThermalModels
... analogously to input models.

### PR DESCRIPTION
**Pull request by ckittl**
Closes #1

_Attention:_ The former ```qDemand``` fields have changed to ```qDot``` and are of (correct) type power. As with the electrical models a positive value denotes consumption of heat power.

### CODE REVIEW

**Comment by ckittl** [comment]
!test

**Comment by ckittl** [comment]
!test

**Comment by ckittl** [comment]
!test

**Comment by johanneshiry** [comment]
!test

**Comment by johanneshiry** [comment]
!test

**Pull request merged**
