### PR TITLE
Misleading parameter name 'height' has changed to 'elevationAngle'

### LINKED ISSUE #393: Misleading parameter name `height` in PvInput
The parameter that specifies the elevation angle of the panel is called `height`. Renaming it to `elevationAngle` would be more declarative.

### PR DESCRIPTION
**Pull request by muradjava**
Misleading parameter name 'height' has changed to 'elevationAngle'

resolves #393

### CODE REVIEW

**Comment by ckittl** [comment]
https://github.com/ie3-institute/PowerSystemDataModel/blob/b1cd187d016978eb75f3281f2d0c1e632baa7972/gradle/scripts/tests.gradle#L4

If you might change the list to `"skipped", "failed"`, the log file won't be blown up by entries for tests, that are passing.

**Comment by ckittl** [comment]
> https://github.com/ie3-institute/PowerSystemDataModel/blob/b1cd187d016978eb75f3281f2d0c1e632baa7972/gradle/scripts/tests.gradle#L4
> 
> If you might change the list to `"skipped", "failed"`, the log file won't be blown up by entries for tests, that are passing.

Nevermind, I already brought it in from another PR.

**Comment by ckittl** [comment]
Please also add a remark in CHANGELOG.md, that describes the changes and that does warn about the fact, that these changes are breaking! You may have a look at the description of the changed transformer parameter interpretation.

**Comment by danielfeismann** [comment]
> Please also add a remark in CHANGELOG.md, that describes the changes and that does warn about the fact, that these changes are breaking! You may have a look at the description of the changed transformer parameter interpretation.

done

**Review by ckittl — APPROVED** [review]

**Pull request merged**
