### PR TITLE
Fixing two winding transformer remark

### LINKED ISSUE #381: Fix a remark in the type model of a two winding transformer
For the attribute xSc it says in the remarks that it is the short circuit reactance, but this should be the short circuit impedance.

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #381

### CODE REVIEW

**Review by danielfeismann — COMMENTED** [review]
Thanks for your work, this looks all good to me. Please also adapt for the test.
- GridTestData.groovy
- ConnectorValidationUtilsTest.groovy 
- ValidationUtilsTest.groovy

**Review by staudtMarius — COMMENTED** [review]
Adapted the mentioned tests

**Review by danielfeismann — COMMENTED** [review]
@staudtMarius: Thank you, I think you missed the ADMITTANCE_PER_LENGTH at GridTestData.groovy (Lines 322 and 323). And the CI isn't going through. Please have a look.
grafik

**Review by staudtMarius — COMMENTED** [review]
I have replaced the two units. Also CI now goes through.

**Review by danielfeismann — DISMISSED** [review]
Looks good, thanks for your work!

**Review by danielfeismann — APPROVED** [review]
Thanks for your work!

**Pull request merged**
