### PR TITLE
Mapping external time series to models

### LINKED ISSUE #51: Mapping external time series to models
It should be possible to give detailed model parameters as well as fixed provided time series for each model. Therefore, a mapping from model to time series is provided.

### PR DESCRIPTION
**Pull request by ckittl**
Resolves #51

### CODE REVIEW

**Comment by ckittl** [comment]
!test

**Comment by ckittl** [comment]
!test

**Comment by ckittl** [comment]
!test

**Comment by johanneshiry** [comment]
!test

**Comment by ckittl** [comment]
!test

**Pull request merged**
