### PR TITLE
Mk/#8 replace optional use

### PR DESCRIPTION
**Pull request by mia-krause**
Regarding issue #8

### CODE REVIEW

**Comment by johanneshiry** [comment]
@mia-krause pls let me know when this is ready for review

**Comment by mia-krause** [comment]
@jhiry it is ready for review, but jenkins & codecov failed. I can't check the jenkins problems from home and codecov doesn't semm to tell me anything either. Could you have a look?

**Comment by johanneshiry** [comment]
!test

**Comment by mia-krause** [comment]
!test

**Comment by mia-krause** [comment]
!test

**Comment by mia-krause** [comment]
!test

**Comment by mia-krause** [comment]
!test

**Comment by mia-krause** [comment]
Cannot satisfy trais + codacy at the same time as codacy does not want wildcard imports, but spotless loves them and sums multiple singular imports to wildcards import. But tests are finished :woman_shrugging:

**Comment by johanneshiry** [comment]
!test

**Comment by johanneshiry** [comment]
@mia-krause please ignore wildcard issues in codacy - will disable this rule asap as I think this rule is pointless. Anyway you missed calling spotlessApply() (reason for travis failure). I fixed that. :-)

Thanks for your work - will merge this now. Please consider using spock next time for your tests instead of JUnit. But that might be a personal preference. :-)

**Pull request merged**
