### PR TITLE
Pp/#875 fix electricvehicle documentation

### PR DESCRIPTION
**Pull request by pierrepetersmeier**
Has this Issue been processed before? I haven't noticed any significant changes.

### CODE REVIEW

**Comment by pierrepetersmeier** [comment]
- added Remarks in docs/readthedocs/models/input/participant/ev.md and docs/readthedocs/models/result/participant/ev.md

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
At first glance, the entity model is missing a table row for `qCharacteristics` (check `EvInput.java`). Other than that, maybe @t-ober remembers what this issue was about.

The additional explanatory commentary you provided here does not seem necessary to me, as it is missing for (all) other documentation of system participants as well.

**Review by staudtMarius — APPROVED** [review]
Seems good to me.

**Comment by t-ober** [comment]
image

The ev is missing the descprition of its attribute type EvTypeInput and the descrption of the type itself, similar to line and line_type

**Review by t-ober — CHANGES_REQUESTED** [review]
We are missing the description of the ev type attribute: 

image

and the table for all type attributes, similar to lines and line types etc.

**Comment by t-ober** [comment]
> We are missing the description of the ev type attribute:
> 
> image
> 
> and the table for all type attributes, similar to lines and line types etc.

Okay nevermind: 

My PSDM docs link was outdated and brought me to some old version.. Sorry for the confusion!

**Review by t-ober — DISMISSED** [review]

**Pull request merged**
