### PR TITLE
Es/#255 time util

### PR DESCRIPTION
**Pull request by EikeSan**
refactor(timeutil): change deprecated TimeTools to TimeUtil

Changed the use of TimeTools for TimeUtil

#225

### CODE REVIEW

**Comment by EikeSan** [comment]
@ckittl The CI again :cry:

**Comment by johanneshiry** [comment]
Hi @EikeSan - first of all: thank you very much for your contribution. As @ckittl already discovered, we are not covering the case merging a branch from a fork yet.  I'm aware of this issue and will try to address it asap. Sorry for the inconvenience.

**Comment by EikeSan** [comment]
@johanneshiry Thanks for the feedback :smile:

**Comment by johanneshiry** [comment]
Short update from my side: dived a little bit more into how to build PRs from forks and how we can integrate this in our current CI pipeline script and setup. Looks like it will take me some time to make it work. Will keep you updated and report back as soon as I have it ready.

**Comment by johanneshiry** [comment]
!test

**Comment by johanneshiry** [comment]
Alright guys, 
I got the CI working with forked repos. However, sonarqube analysis does not support forked repos at the moment. Hence the results from sonarqube needs to be ignored for now as I cannot guarantee that they make sense.

**Comment by EikeSan** [comment]
@ckittl I can't see the codecov changes to solve it. 😞

**Comment by ckittl** [comment]
> @ckittl I can't see the codecov changes to solve it. 😞

No worries, I suppose it was a temporary issue, as it now is possible to access the results without login. Anyways, the coverage decrease is so small, that I will ignore it anyways. As you didn't change much of logic, it's totally fine. 😃

**Review by ckittl — APPROVED** [review]
Thanks a lot for your work on this issue! I only did some minor adaptions to ensure, that all result factories use the same time util. This also decreased the amount of changed lines, which makes Codecov happier. :-)

**Comment by johanneshiry** [comment]
Side note: looks like in contrast to my assumptions that sonarqube is indeed at least taking into account the changes on the forked branch after the CI reconfiguration. 🎉

**Pull request merged**
